DROP TYPE FREEZE_TYPE;

ALTER TYPE FREEZE_STATUS RENAME VALUE 'awaiting' TO 'active';

ALTER TABLE "freeze" RENAME COLUMN "time" TO "start";
ALTER TABLE "freeze" ADD COLUMN "finish" TIMESTAMP NOT NULL;
ALTER TABLE "freeze" DROP COLUMN "type";